# Generated by Django 4.2.7 on 2023-12-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compania', models.CharField(max_length=200)),
                ('servicio', models.CharField(max_length=200)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puerto', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crusero_app.continente')),
            ],
        ),
        migrations.CreateModel(
            name='CompaniasContinente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crusero_app.compania')),
                ('id_continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crusero_app.continente')),
            ],
        ),
    ]
